<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_70000151884951001</name>
   <tag></tag>
   <elementGuidId>b3d3fea1-1859-4c15-b099-a14c6c391d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='account'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cc25c81-aa5d-46e0-8bc3-34e544596058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>d9ecaa30-331f-47eb-9b03-bb1241956541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-link</value>
      <webElementGuid>005e5851-6c42-4b5c-b78f-ee4a50f48491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>70000151884951001</value>
      <webElementGuid>6a9372bb-dc34-470a-ae72-4551879f2cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;layout-fixed&quot;]/lib-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper ng-star-inserted&quot;]/div[1]/app-account[@class=&quot;ng-star-inserted&quot;]/app-account-search[1]/main[1]/div[@class=&quot;account-search-mn mt-2 ng-star-inserted&quot;]/app-search-results[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mt-2&quot;]/table[@class=&quot;mat-table cdk-table mat-sort address account-search-table-mn&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-AccountNumber mat-column-AccountNumber ng-star-inserted&quot;]/a[@id=&quot;account&quot;]</value>
      <webElementGuid>6fda8263-5b37-44ee-bb4f-fa9b718f7735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CSR_LM_Login/Page_Loan Manager - Account Search/iframe</value>
      <webElementGuid>5c4d4483-71d5-4f9f-bc47-2be0433c1915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='account'])[3]</value>
      <webElementGuid>af58703d-423f-4037-80e6-b4d300c9783f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'70000151884951001')]</value>
      <webElementGuid>d27a2870-5bcf-4434-9ff6-640cd23fce34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VINPW12V19FA10929'])[1]/following::a[1]</value>
      <webElementGuid>81576042-4553-4ae9-a4fb-73a0fa835b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BLACK50033@GENERAL.COM'])[1]/following::a[1]</value>
      <webElementGuid>f85986c0-ebc7-4cc4-ba9a-5027d83fd4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan'])[3]/preceding::a[1]</value>
      <webElementGuid>05e903c4-f654-4ff5-b9a5-855df31d1977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKEEYA BLACK'])[1]/preceding::a[1]</value>
      <webElementGuid>711cd272-5545-492f-82cb-9ee6478e7729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='70000151884951001']/parent::*</value>
      <webElementGuid>22b0646f-a95d-4806-a0fa-b6910692d349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>c4effb02-fec3-4169-8f8f-a582ac6cdb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'account' and (text() = '70000151884951001' or . = '70000151884951001')]</value>
      <webElementGuid>766e539b-e22f-44a9-8b30-ecacf91e31d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
