<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign In_username</name>
   <tag></tag>
   <elementGuidId>fade2d47-755d-4023-911a-92911bcfa0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9ee3a9e-0066-4b16-8988-c65a85f41349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>827da984-b9b6-432e-81aa-560a49ad3c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>412f32ca-080c-4c9b-ae7f-97a2cefbc1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>dcd19ed0-d798-4d13-9c0c-7291dcda03f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fce97b3e-29b2-4f18-99bd-eaf55b3e53af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>loginData.UserName</value>
      <webElementGuid>523016ec-c7e0-47ba-a4fd-19abbee1f553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8b9f940a-ad3f-4d29-a8a3-18228beca747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-invalid-required</value>
      <webElementGuid>f5102b7f-188b-45ce-9fad-90f29b252eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-ui-enabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53cb3a98-3b57-4a5b-a93c-469d440486ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-panel&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;text-left mb-lg ng-pristine ng-invalid ng-invalid-required&quot;]/div[@class=&quot;form-group has-feedback mb-sm&quot;]/input[@class=&quot;form-control ng-pristine ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>d9dbf860-60c7-4b46-a5f2-d344a8e2c065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>755a5d03-f193-4dcc-a7d6-90022a6b3554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-panel']/div[2]/form/div[3]/input</value>
      <webElementGuid>825fd147-f49c-4342-b91e-76a09c264452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5477d9dd-4b44-4558-a72a-709eccb2180e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>dabd24b7-dd9b-4f5a-968f-ab4ac680b591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
