<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Remember Me_fa fa-check</name>
   <tag></tag>
   <elementGuidId>e937826a-ad64-4a9c-932a-dca9264f1f61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-panel']/div[2]/form/div[7]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1fc07aa4-5cbc-448b-9c9b-143ffe0a0ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check</value>
      <webElementGuid>5f25887b-fd32-4aa8-a879-7258414acddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-panel&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;text-left mb-lg ng-dirty ng-valid ng-valid-required&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;checkbox c-checkbox pull-left mt0&quot;]/label[1]/span[@class=&quot;fa fa-check&quot;]</value>
      <webElementGuid>6aa4788b-148a-4aae-8ef3-d2be9ecf72d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-panel']/div[2]/form/div[7]/div/label/span</value>
      <webElementGuid>fb103482-8707-4053-ab4c-39e51fbb9dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>d9551b21-8efe-4643-acb4-38b3231d0ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
