<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab-heading_Supplemental</name>
   <tag></tag>
   <elementGuidId>e7e4324f-72ce-4f0b-a91d-42cc6bcd01d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[2]/preceding::tab-heading[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Supplemental&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tab-heading</value>
      <webElementGuid>3960422a-2b5d-418a-b1bb-ce9d8c050693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': (supplementalActive) ? 'brown' : 'darkslategrey' }</value>
      <webElementGuid>e928d6f5-4214-440a-a6ed-947a1046e32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>43615b7c-5199-4a0d-ac75-d59e198efa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Supplemental
                    </value>
      <webElementGuid>feb66488-11f2-444c-8f82-66065de139d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths ng-scope js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@class=&quot;layout-fixed dialer-collapsed&quot;]/div[@class=&quot;wrapper timeoutTest ng-scope ng-fadeInDown&quot;]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-wrapper ng-scope ng-fadeInDown&quot;]/div[@class=&quot;slider-container ng-scope&quot;]/div[1]/div[@class=&quot;loanInfo&quot;]/div[@class=&quot;bg-white p0 m0 mt-sm ng-isolate-scope&quot;]/ul[@class=&quot;nav nav-tabs nav-justified&quot;]/li[@class=&quot;ng-isolate-scope&quot;]/a[@class=&quot;ng-binding&quot;]/tab-heading[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>18783ddc-a8f5-453a-8d54-39a90f0fba5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[2]/preceding::tab-heading[1]</value>
      <webElementGuid>8fa006ca-8056-4603-b8e1-01ab1d71a9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal Balance'])[1]/preceding::tab-heading[1]</value>
      <webElementGuid>b0179a0d-0fda-4fcf-a656-3dd517f03eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Supplemental']/parent::*</value>
      <webElementGuid>e43364b7-9653-4c1c-bda7-40149a098f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/tab-heading</value>
      <webElementGuid>2ee0d863-49b8-4e9f-9524-0b7bc4f15a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tab-heading[(text() = '
                        Supplemental
                    ' or . = '
                        Supplemental
                    ')]</value>
      <webElementGuid>92d45622-b660-477b-93f2-5b9996bbc837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
