<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>cabab162-7705-4c5e-b67f-9c917d8b5ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_info_cancel_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='customer_info_cancel_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7414bf2-b54c-4f0b-9ddc-0b8278d0adfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f9ebc992-fb48-4fb4-9c34-238e97ad6c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>greybtn2 ng-tns-c256-6 ng-star-inserted</value>
      <webElementGuid>4f719f42-d60e-43ff-937d-fb258da51d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_info_cancel_0</value>
      <webElementGuid>166b393a-108e-48f7-995d-cd1699beb84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel </value>
      <webElementGuid>fdee2f6f-a530-4c31-84c2-4e6157a4d22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_info_cancel_0&quot;)</value>
      <webElementGuid>37140c02-19e6-4df1-98a1-b92319ddf6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>b45b2353-a837-48d9-ab11-8632961101ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='customer_info_cancel_0']</value>
      <webElementGuid>3cc58653-bb48-422f-8632-b2a1cf788e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_custInfo_table']/tbody/tr[2]/td/div/form/div/div[2]/button[2]</value>
      <webElementGuid>e907614f-8428-4d4e-8fb8-194d3bd0b576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>27c550e8-9427-42e8-ac2f-7d0bf5cf3816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All fields with an *(asterisk) are required to save.'])[1]/following::button[2]</value>
      <webElementGuid>1e1b048c-295b-49dc-a1dd-816669a2beb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Last Verified com'])[1]/preceding::button[2]</value>
      <webElementGuid>035856a2-1da4-4b07-a598-445fde85b11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr'])[2]/preceding::button[2]</value>
      <webElementGuid>504909d3-2809-4053-8942-159a0808b82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>01f978fc-f286-4367-8301-1b31d1fed8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>c3c89e4c-5f2d-404c-b1d9-f0cfc5b089e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'customer_info_cancel_0' and (text() = ' Cancel ' or . = ' Cancel ')]</value>
      <webElementGuid>a31756e6-1886-4482-92f9-240b6946f33f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
