<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Open_myIframe</name>
   <tag></tag>
   <elementGuidId>0433ca1d-8df6-454b-9916-4250059b5f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='myIframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cac50f57-8917-44b2-8568-95852772edfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://toyotaqa.loanmanager.central.conduent.com/ReleaseTest/csr/csrnew/#/dashboard/customer/customerinfo/IL</value>
      <webElementGuid>68b4b8d4-3f64-4e99-9d95-4b9c14cee56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myIframe</value>
      <webElementGuid>ef36036f-7804-4e97-991a-302431224585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-nofocus</value>
      <webElementGuid>c45f2c1c-8411-4648-b96e-fcbf82c4abfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>111f81d1-fad9-49cd-9c89-2d021b5bd5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this);</value>
      <webElementGuid>e3f63362-4d05-4505-9bb0-456be0fa991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myIframe&quot;)</value>
      <webElementGuid>eecec663-e0c3-48c1-a4ea-a339680c0e8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='myIframe']</value>
      <webElementGuid>ca2c76df-528c-41f9-94b9-9148779ff7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1460f80d-4dfa-4893-bf91-e3d5c6d186f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://toyotaqa.loanmanager.central.conduent.com/ReleaseTest/csr/csrnew/#/dashboard/customer/customerinfo/IL' and @id = 'myIframe']</value>
      <webElementGuid>5b7826b7-959b-4a1f-9ff3-670369e4caa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
