<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_id_inp_custInfo_LastName_1</name>
   <tag></tag>
   <elementGuidId>56e6342d-a8e6-4e8f-a411-2edcc385ea01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_inp_custInfo_LastName_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_inp_custInfo_LastName_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1908e8e-ce73-4225-903a-dbc3110329b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb49c88d-2cf9-4970-8935-69f933582117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>7c7dbfc1-aa70-450a-8915-414a1273b5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>68c3afe6-882b-4813-8de3-c45e2cb6ac34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^!();_ .\-a-zA-Z0-9]/g, '');</value>
      <webElementGuid>b5b300f4-7b64-4f21-9ac5-0947f8252fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control control-large-size ng-tns-c256-6 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>e538130c-9406-4169-8d55-7def4f211ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_inp_custInfo_LastName_1</value>
      <webElementGuid>5612e875-9179-484a-9f56-fe1b06365572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0122a023-6ffb-4bfb-983d-a7ab8c9650dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e96eb29e-86e0-41ae-bbea-e3c17404f32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_inp_custInfo_LastName_1&quot;)</value>
      <webElementGuid>34eaecf3-9286-418f-a943-4203fdd7260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>b9bc8344-6702-40ed-95ad-a4f82ff284e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_inp_custInfo_LastName_1']</value>
      <webElementGuid>436209fe-821a-40d4-8031-259a463f300a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_custInfo_table']/tbody/tr[2]/td/div/form/div[2]/div/table/tr[5]/td/div/div/mat-form-field/div/div/div/span/input</value>
      <webElementGuid>e8a588b0-e61e-4bfb-a38b-b428d7adc6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d67a9edb-5c59-4f09-912a-dd6c7ac43038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_inp_custInfo_LastName_1']</value>
      <webElementGuid>3d304c4f-bc4d-4179-ac8c-98a97a1cb9c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
