<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name12_id_inp_custInfo_MiddleName_1</name>
   <tag></tag>
   <elementGuidId>34575de1-39a8-4da3-8b1b-1bcb665527fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_inp_custInfo_MiddleName_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_inp_custInfo_MiddleName_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2228c3e0-ff93-4325-9690-c9211cc5d6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e48cabf-c07f-42ae-8e3c-2be775bedc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>MI</value>
      <webElementGuid>7108d001-28a1-40a9-97f6-ff284704bba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d9cfd2d3-4734-47d1-84ee-2f86acb6f480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^!();_ .\-a-zA-Z0-9]/g, '');</value>
      <webElementGuid>580f0ae5-2507-4afd-a4d3-dc9c121a6aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control control-large-size ng-tns-c54-30 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>2f0b8e51-c55f-416f-ae78-c3952ac93db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_inp_custInfo_MiddleName_1</value>
      <webElementGuid>4e2cfd03-474b-443f-8085-94f57d8e4441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8465737-994c-4be1-9f13-2aaffb134c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35621131-399a-43ba-9a00-8c3c358b2bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_inp_custInfo_MiddleName_1&quot;)</value>
      <webElementGuid>73339070-41ad-4a2a-90ec-9fe154cc1085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>fb22b094-b713-4d21-8b21-c34129910b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_inp_custInfo_MiddleName_1']</value>
      <webElementGuid>c99f8175-d2a6-4916-9b19-a7fefbd0602b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_custInfo_table']/tbody/tr[2]/td/div/form/div[2]/div/table/tr[4]/td/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>b3622fc5-bdf8-43d7-a6bc-70ecf77fce7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>df2a3ef3-6b43-4b91-b396-2c535f3090d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_inp_custInfo_MiddleName_1']</value>
      <webElementGuid>03cdaa8e-67c2-42e0-9750-9781bd02014a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
