<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prefix TEST 700_id_inp_custInfo_FirstName_1</name>
   <tag></tag>
   <elementGuidId>ace5a900-55a7-4a8b-8c7d-9835558adf9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_inp_custInfo_FirstName_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_inp_custInfo_FirstName_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50340b9b-5128-4b44-99de-b90a1280007f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a1dd3c0-c71b-426f-8a3a-1c19d49a1f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>15b14db3-1048-4cf6-ad25-7d3dc36f32e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>263c80aa-48af-41ac-ab36-d914763fa6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^!();_ .\-a-zA-Z0-9]/g, '');</value>
      <webElementGuid>0b98e2f0-bb59-418e-8123-c83539ade563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control control-large-size ng-tns-c54-29 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>9f2623ea-5ed1-4835-994d-c771acfbb2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_inp_custInfo_FirstName_1</value>
      <webElementGuid>d13e4983-1ce1-432e-be53-cc243a0c3714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b77eb69-20de-4e5c-9c5b-225f1910629f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>013f9a62-c886-4b2e-9dd2-07a0bb317491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_inp_custInfo_FirstName_1&quot;)</value>
      <webElementGuid>e55b0751-cbd9-4de8-806a-0cc010925256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>b2d95be7-4121-425b-84df-9b25e9c7eb37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_inp_custInfo_FirstName_1']</value>
      <webElementGuid>73e07284-5aac-4341-bfa5-825c2126ee8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_custInfo_table']/tbody/tr[2]/td/div/form/div[2]/div/table/tr[3]/td/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>609b56db-d332-4318-8c85-97665cbbcecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>fb6a3431-8689-4865-a777-94ffd5e6ba7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_inp_custInfo_FirstName_1']</value>
      <webElementGuid>7a7002c4-8360-415c-a897-a79e39f7fb2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
