<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A1</name>
   <tag></tag>
   <elementGuidId>1323be09-c5b0-480e-9e10-96a47056e7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_moption_xm2_generation_10290_A1 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='id_moption_xm2_generation_10290_A1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84c42b7c-da2d-4ca3-a058-d99d185a3659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>91361306-c727-4a44-895a-597154faddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> A1 </value>
      <webElementGuid>a66e95e1-0779-4955-adad-1bf3c5d46a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_moption_xm2_generation_10290_A1&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>52571fec-1440-4d85-9595-dd3879e3668f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>69c286b7-8d17-4d8f-a3a9-76563d709cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='id_moption_xm2_generation_10290_A1']/span</value>
      <webElementGuid>f41d730e-4615-490c-b9de-2be323d74009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A111'])[1]/following::span[1]</value>
      <webElementGuid>3c9070e5-6324-418d-94f5-901b9b3cd39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='II'])[1]/following::span[2]</value>
      <webElementGuid>21ee5ee9-0866-42c3-ba39-3c46626eea6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A222'])[1]/preceding::span[1]</value>
      <webElementGuid>b6061960-f4de-4ba6-8a31-6bc589d8bbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I'])[1]/preceding::span[2]</value>
      <webElementGuid>e67b8a8e-7e9f-4ca0-ae77-5c95b39665e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A1']/parent::*</value>
      <webElementGuid>28cc53df-9c7f-499a-a4e7-84228d97878b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>cfcf23f8-2946-44fb-9f1e-df389e291314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' A1 ' or . = ' A1 ')]</value>
      <webElementGuid>8bc4aa08-0d87-4894-8e31-ed85d6cefafc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
