<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_DOUGLAS BLACK</name>
   <tag></tag>
   <elementGuidId>eb8d0d8d-3e1f-4250-a74c-b042f829dc31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_row_custInfo_history_CustomerName_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='id_row_custInfo_history_CustomerName_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>92c51123-d114-4309-956f-8b126b85ed4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>1f2826f2-f82c-45b2-88cd-4aaea781a091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-CustomerName mat-column-CustomerName ng-star-inserted</value>
      <webElementGuid>7568f01b-c25f-4737-b88c-bf0db61554fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_row_custInfo_history_CustomerName_0</value>
      <webElementGuid>f67f5522-0225-40a4-aeb8-9d48e280b1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOUGLAS BLACK </value>
      <webElementGuid>341c02ff-cee2-4a3e-b776-1ba7272fee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_row_custInfo_history_CustomerName_0&quot;)</value>
      <webElementGuid>cee7d3c7-392b-4779-8f6f-46555eae441e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>d6d7f6e2-ea28-4c37-91a7-ddb193e9fc96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='id_row_custInfo_history_CustomerName_0']</value>
      <webElementGuid>6d3cca44-f0e0-467c-aac7-6108ab291b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_custInfo_table']/tbody/tr[2]/td/div/app-customer-info-history/div/table/tbody/tr/td[3]</value>
      <webElementGuid>554842c9-6200-49b2-b83a-55323c06a1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAKH'])[2]/following::td[1]</value>
      <webElementGuid>83533252-3af8-4b90-bbb2-84030d5e6a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[2]/following::td[3]</value>
      <webElementGuid>288b3f64-4bf3-4a45-94d7-5a8fdffbd264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(XXX)-X99-9999'])[2]/preceding::td[1]</value>
      <webElementGuid>cfeef42f-c4ff-4d63-9242-caa7b6bed625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Opt-in'])[7]/preceding::td[1]</value>
      <webElementGuid>60573865-3310-47f0-89cc-fb1184fbcf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DOUGLAS BLACK']/parent::*</value>
      <webElementGuid>dbf28621-fa02-4445-8eee-f8c0ac6f4a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-customer-info-history/div/table/tbody/tr/td[3]</value>
      <webElementGuid>ae656dca-c1a3-4523-a65d-4582eeb218d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'id_row_custInfo_history_CustomerName_0' and (text() = 'DOUGLAS BLACK ' or . = 'DOUGLAS BLACK ')]</value>
      <webElementGuid>abb036ae-9a20-4f91-80b0-54abacf4c60d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
