<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Account Management_loan_mgt</name>
   <tag></tag>
   <elementGuidId>39eabb93-2966-4934-9d69-bce13aa64d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='loan_mgt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loan_mgt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loan_mgt</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>569d2285-b192-472a-88d8-40816406f612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aab742ab-e100-49b7-8e16-03ec305969c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loan_mgt</value>
      <webElementGuid>ed4e1ade-ecb5-4067-89ef-82766b12ecbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$root.user.role.Functions.AccountManagement.IsEdit = true;loanManagementEditClick()</value>
      <webElementGuid>92292ff4-572f-4f55-8e5f-a4d6df55617f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-default</value>
      <webElementGuid>2f05ee9b-1523-423e-84a7-b612a7367928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan_mgt&quot;)</value>
      <webElementGuid>599c74d9-97f7-461c-a198-8f87ca9ec8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='loan_mgt']</value>
      <webElementGuid>6b12bf19-bb36-4122-bde9-9f3e322080c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loanMngmnt']/div/div/div/button</value>
      <webElementGuid>cd545ae1-ecfe-484b-a862-777ce29a849f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Management'])[1]/following::button[1]</value>
      <webElementGuid>3a39c2fe-d1d8-41e0-9c2e-e294541c07ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed To Posting Code'])[1]/preceding::button[3]</value>
      <webElementGuid>438522cf-da94-454b-bf1c-251aeb8f11ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection Officer'])[1]/preceding::button[3]</value>
      <webElementGuid>351b4e62-1f5b-4e86-a4f9-1d2edbd0260f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>a8b505de-7614-466e-a1d4-72f1577abed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'loan_mgt']</value>
      <webElementGuid>793a80bb-85a8-4645-bebb-833ea123308a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
