<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Account Management_fa fa-save</name>
   <tag></tag>
   <elementGuidId>d709aeba-a9e9-472c-8a3a-089caf4f78c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='loan_mgmt']/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.fa.fa-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>60dda572-04e6-40ca-b63d-8a1dd12326e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-save</value>
      <webElementGuid>b8d110a3-2530-4758-8642-7bf2a68ce338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan_mgmt&quot;)/em[@class=&quot;fa fa-save&quot;]</value>
      <webElementGuid>797a088e-6fd5-4bda-87c3-6023bd31cb9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='loan_mgmt']/em</value>
      <webElementGuid>1ff12e9b-b5cc-4eca-8929-1563aeb5f4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/button/em</value>
      <webElementGuid>9da4bce0-e9b5-445f-b2b7-f6d697368b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
