<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Control Level 2_loan_AM_20</name>
   <tag></tag>
   <elementGuidId>8adf0427-2aec-4f37-8f70-71e80395a4e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loan_AM_20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loan_AM_20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loan_AM_20</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81c7adea-92d4-45f7-aa75-37c5b2056903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loan_AM_20</value>
      <webElementGuid>3d3a1f9c-abc0-4c50-94ca-7227ba2dcc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>getLoanManagementUdt(prop.Value,prop.Value,prop.Name,false)</value>
      <webElementGuid>918d9de9-09e1-4528-82b9-64e06772ddfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mydirectivevar</name>
      <type>Main</type>
      <value>prop.Value</value>
      <webElementGuid>181e5373-1477-483f-b81d-047565aeca00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mydirectivename</name>
      <type>Main</type>
      <value>prop.Name</value>
      <webElementGuid>40c246cc-9646-431d-ba1a-e5a3229de345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatypevalue</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>bdde3991-d6b6-4b06-94e0-01bc0fd2911d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2835fd5a-c639-414e-9047-e282112e56c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayvalue</name>
      <type>Main</type>
      <value>000</value>
      <webElementGuid>afce9e34-af5d-4739-b2af-f966ee70d73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>prop.Value</value>
      <webElementGuid>7ea5d1af-1249-4704-832d-ea458f22caa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>callbackfn</name>
      <type>Main</type>
      <value>getLoanManagementUdt(prop.Value,prop.Value,prop.Name,false)</value>
      <webElementGuid>97df15de-ccf5-4a96-a4c1-3eee0d14e4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid</value>
      <webElementGuid>95708124-c9d5-4676-9636-2d6ea1ba6d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan_AM_20&quot;)</value>
      <webElementGuid>d783fe52-4b74-4977-8f09-4ec0d6693e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loan_AM_20']</value>
      <webElementGuid>e6267ff8-a798-472e-b168-eaf716055ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loanMngmnt']/div[2]/form/div/div/div[21]/table/tbody/tr/td[2]/div/div/div/div/input</value>
      <webElementGuid>ee6d009d-4c2a-4fd3-8d73-1f9635b13aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/table/tbody/tr/td[2]/div/div/div/div/input</value>
      <webElementGuid>9049bd62-1e6a-4588-8da2-23b01d02e07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loan_AM_20']</value>
      <webElementGuid>200b20fc-3f2f-4289-8762-ba714e2b166c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
