<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Control Level 1_loan_AM_17</name>
   <tag></tag>
   <elementGuidId>14149c5f-f8da-4339-b40e-e6304bf7c002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loan_AM_17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loan_AM_17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loan_AM_17</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>198082b2-98d8-453f-8ae6-546f1ddde6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loan_AM_17</value>
      <webElementGuid>b7ea338e-dc6a-4a25-a6c0-8bc3a59912c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>getLoanManagementUdt(prop.Value,prop.Value,prop.Name,false)</value>
      <webElementGuid>1dc268dc-efc3-4281-8b2a-d72d52e287dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mydirectivevar</name>
      <type>Main</type>
      <value>prop.Value</value>
      <webElementGuid>6b772429-d5f4-48f9-829c-0bf42d1149fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mydirectivename</name>
      <type>Main</type>
      <value>prop.Name</value>
      <webElementGuid>5b7e0280-c03a-41a8-ae02-03ec895845c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatypevalue</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>99c261dc-3c3c-4daa-bdd7-0378f4b71f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>933028bd-e2c8-4f3a-8241-c5186faa3db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayvalue</name>
      <type>Main</type>
      <value>001</value>
      <webElementGuid>ccdf9371-09fe-415a-811e-47440a0f9ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>prop.Value</value>
      <webElementGuid>f1ec83eb-1ddb-4fd1-a245-d4c8e73c4358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>callbackfn</name>
      <type>Main</type>
      <value>getLoanManagementUdt(prop.Value,prop.Value,prop.Name,false)</value>
      <webElementGuid>58921b2a-bb4c-49f3-a236-7127acbde4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid</value>
      <webElementGuid>a7824437-7a14-455c-94cc-e376cb13ced8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loan_AM_17&quot;)</value>
      <webElementGuid>2b81b08b-5ba1-4eb9-bc2c-d96735986c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loan_AM_17']</value>
      <webElementGuid>def8a4ab-2e1c-475e-9d0d-4035fda11f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loanMngmnt']/div[2]/form/div/div/div[18]/table/tbody/tr/td[2]/div/div/div/div/input</value>
      <webElementGuid>3e85959b-2215-43ff-adfe-72c7e7978c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr/td[2]/div/div/div/div/input</value>
      <webElementGuid>686ba9d4-67dd-4f84-b9cd-eae82f8f223d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loan_AM_17']</value>
      <webElementGuid>516b1f28-d77e-452f-a0c9-f5351a280a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
