<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Customer Info</name>
   <tag></tag>
   <elementGuidId>2f21793c-df34-4627-baac-2c472ed9c04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#side_nav_12 > #item > #xa_sidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xa_sidebar'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ab94545-24a2-47b0-aebb-e7230f4fafc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xa_sidebar</value>
      <webElementGuid>3a721b81-d8c5-40b5-84c2-56de660eca43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>sidebar.nav.customer.CUSTOMERINFO</value>
      <webElementGuid>2f80a570-2f58-4803-bd6f-957ea2699781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope ng-binding</value>
      <webElementGuid>4a13c3e6-c738-4ccc-9f4e-846e53d80efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Info</value>
      <webElementGuid>997ad849-5289-4a52-9a96-e4a6de872c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side_nav_12&quot;)/a[@id=&quot;item&quot;]/span[@id=&quot;xa_sidebar&quot;]</value>
      <webElementGuid>5a4dd7be-4ba6-46de-9ae2-b6d5e09f2838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xa_sidebar'])[12]</value>
      <webElementGuid>ba0429f0-eaf3-4199-acb7-59ad0034838f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='item']/span)[11]</value>
      <webElementGuid>95eafa45-cac8-4055-a911-c3903fe7e5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::span[1]</value>
      <webElementGuid>b62df06b-4f10-4b81-b7f5-4d747ad032eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance History'])[1]/following::span[2]</value>
      <webElementGuid>e96099a8-a14c-4ead-aa8b-19e937e723fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Services'])[1]/preceding::span[1]</value>
      <webElementGuid>53ca4c18-5fb2-4997-91e7-36c487877d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bankruptcy'])[1]/preceding::span[2]</value>
      <webElementGuid>2c9ce0a9-4347-47de-80dc-c879324de65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Info']/parent::*</value>
      <webElementGuid>97c2c6ba-c032-4539-8a2b-3c402cb2dd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a/span</value>
      <webElementGuid>2d0fafd8-3dc7-43f6-b01c-7ff25d3314fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xa_sidebar' and (text() = 'Customer Info' or . = 'Customer Info')]</value>
      <webElementGuid>fadeba0c-2503-4c62-9348-eb1296e0ad66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
