<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Account</name>
   <tag></tag>
   <elementGuidId>fce7f94a-da74-4f89-8673-b63129169724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#side_nav_5 > #item > #xa_sidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xa_sidebar'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9e48364-22a4-4221-88db-3f522e75bd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xa_sidebar</value>
      <webElementGuid>66a21cc4-53d9-4b91-987e-1ba846a03d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>sidebar.nav.loan.LOAN</value>
      <webElementGuid>3619319e-7ddd-49f7-ab52-9f563831b156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope ng-binding</value>
      <webElementGuid>857b66c6-7062-48b9-9a38-ee27c55a5d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>143d94f3-51a1-4977-a283-1b6bcc9bfc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side_nav_5&quot;)/a[@id=&quot;item&quot;]/span[@id=&quot;xa_sidebar&quot;]</value>
      <webElementGuid>23fc331c-5211-4bd4-b34e-d64cb95fd899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xa_sidebar'])[4]</value>
      <webElementGuid>61337714-0e41-4cdc-9fb9-ded68090d5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='item']/span)[3]</value>
      <webElementGuid>eac93d16-b19b-4afa-99e2-e2204163ee44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payoff Quote'])[1]/following::span[1]</value>
      <webElementGuid>0cc3540b-9a59-495d-ae11-882112fb2a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[2]</value>
      <webElementGuid>d0dc9299-65f6-4266-ae68-941b8b56359a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Documents'])[1]/preceding::span[1]</value>
      <webElementGuid>b46406e4-d3e3-467f-a53c-ea8c1ecdcf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Documents'])[2]/preceding::span[2]</value>
      <webElementGuid>e26ca143-6525-459a-b88f-4ae8e15bdb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>050f37f1-ff09-4944-acd2-084ba6dd201b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xa_sidebar' and (text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>1795544b-342f-44f4-9728-d180b295b6aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
