<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Topwear</name>
   <tag></tag>
   <elementGuidId>46d5fbef-f56c-4468-8fe9-ad908a5b9359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1907d01-14ba-4dbc-92ec-b269cf0e4131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Topwear</value>
      <webElementGuid>c099a9cc-4576-43cd-a46c-c2625273aef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jBYtJt</value>
      <webElementGuid>dedd4df7-f8a2-4b16-92d0-a1a952b08704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/clothing-and-accessories/topwear/pr?sid=clo,ash&amp;p[]=facets.ideal_for%255B%255D%3DWomen&amp;p[]=facets.ideal_for%255B%255D%3Dwomen&amp;otracker=categorytree&amp;otracker=nmenu_sub_Women_0_Topwear</value>
      <webElementGuid>8731cb25-0baf-44cb-9c90-d1f25a95cb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Topwear</value>
      <webElementGuid>168a4d77-a9f3-4050-8c2f-09622112fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_5M58Mb&quot;]/div[@class=&quot;ACvr7K hTtFMH&quot;]/div[@class=&quot;bpjkJb&quot;]/div[@class=&quot;jzpKY6&quot;]/div[@class=&quot;wZsanD&quot;]/a[@class=&quot;jBYtJt&quot;]</value>
      <webElementGuid>3d885c7c-1594-4f64-a1da-1d8f6f7640b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div/div/a[2]</value>
      <webElementGuid>9612e448-9746-4ed2-aa6c-dfb7d7d621a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Topwear')]</value>
      <webElementGuid>26998170-6519-446c-abae-106ab9ea377a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women Western &amp; Maternity Wear'])[1]/following::a[1]</value>
      <webElementGuid>1be85fa8-2a6b-41a3-8ac8-3d591f90cbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clothing'])[1]/following::a[1]</value>
      <webElementGuid>83daf9c3-e231-4f56-b914-dda71d95e9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dresses'])[1]/preceding::a[1]</value>
      <webElementGuid>281134a3-c70c-4e86-8d38-32050f328495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/preceding::a[2]</value>
      <webElementGuid>f1234364-9b85-4382-aa1a-0f00d25657a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Topwear']/parent::*</value>
      <webElementGuid>5a170540-cc1a-40b5-86e5-9d5bc2fb6e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/clothing-and-accessories/topwear/pr?sid=clo,ash&amp;p[]=facets.ideal_for%255B%255D%3DWomen&amp;p[]=facets.ideal_for%255B%255D%3Dwomen&amp;otracker=categorytree&amp;otracker=nmenu_sub_Women_0_Topwear')]</value>
      <webElementGuid>2c9e931b-dc95-4b3b-82fd-33c2dff15f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a[2]</value>
      <webElementGuid>f2ec06ca-a91d-4629-ac5d-b4317d0fd346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Topwear' and @href = '/clothing-and-accessories/topwear/pr?sid=clo,ash&amp;p[]=facets.ideal_for%255B%255D%3DWomen&amp;p[]=facets.ideal_for%255B%255D%3Dwomen&amp;otracker=categorytree&amp;otracker=nmenu_sub_Women_0_Topwear' and (text() = 'Topwear' or . = 'Topwear')]</value>
      <webElementGuid>dcc328ce-56ea-47cb-b182-90d223fd8349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
