<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_30 or more</name>
   <tag></tag>
   <elementGuidId>359be8dc-dd15-4119-b40c-f2a431355ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._6i1qKy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[5]/div[2]/div/div/div/label/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>494a2416-99e3-4134-9024-05964bfdb1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6i1qKy</value>
      <webElementGuid>1bfa8924-3839-4433-8e7a-b5fa41ae6130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30% or more</value>
      <webElementGuid>2cd428e8-daa7-46c9-80b4-1326063089b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;nt6sNV JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-2-12&quot;]/div[@class=&quot;DOjaWF gdgoEp col-12-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_0BvurA&quot;]/section[@class=&quot;-5qqlC _2OLUF3&quot;]/div[@class=&quot;SDsN9S&quot;]/div[@class=&quot;bs1+1t&quot;]/div[@class=&quot;ewzVkT _3DvUAf&quot;]/div[@class=&quot;QCKZip hpLdC3&quot;]/label[@class=&quot;tJjCVx _3DvUAf&quot;]/div[@class=&quot;_6i1qKy&quot;]</value>
      <webElementGuid>f805877c-f7c5-4fba-9bf5-c24165987e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[5]/div[2]/div/div/div/label/div[2]</value>
      <webElementGuid>7227c2a4-81df-4002-a2f0-ceb189c40a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount'])[1]/following::div[6]</value>
      <webElementGuid>4376f476-97b7-4de5-a486-6119db205658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[8]</value>
      <webElementGuid>ce5813ca-faac-4e10-964e-17909dce46de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size - UK/India'])[1]/preceding::div[17]</value>
      <webElementGuid>4ac264bb-9866-4c26-a020-0058c0afaf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occasion'])[1]/preceding::div[49]</value>
      <webElementGuid>de8b33af-ed10-49ef-912b-29698701cfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30% or more']/parent::*</value>
      <webElementGuid>948816fd-33c1-47d6-896b-2ea400f39f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[2]</value>
      <webElementGuid>269290c8-f828-49db-892a-1dc9847b262a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '30% or more' or . = '30% or more')]</value>
      <webElementGuid>9ef6b752-1049-4966-bc30-e7045ae878ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
