<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Brand_XqNaEv</name>
   <tag></tag>
   <elementGuidId>b149b99b-95f4-4217-b2a0-1ebb2de63ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.XqNaEv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/div[2]/div/div[2]/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6ee7e4d-4d9b-42c2-a867-439aeb776807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>XqNaEv</value>
      <webElementGuid>d1cfc771-bee9-4c98-8863-6d9e0cbdc40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;nt6sNV JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-2-12&quot;]/div[@class=&quot;DOjaWF gdgoEp col-12-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_0BvurA&quot;]/section[@class=&quot;-5qqlC _2OLUF3&quot;]/div[@class=&quot;SDsN9S&quot;]/div[@class=&quot;bs1+1t&quot;]/div[@class=&quot;ewzVkT _3DvUAf&quot;]/div[@class=&quot;QCKZip hpLdC3&quot;]/label[@class=&quot;tJjCVx _3DvUAf&quot;]/div[@class=&quot;XqNaEv&quot;]</value>
      <webElementGuid>432eee37-7e3b-4f4f-b0e4-6f02334c39ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/div[2]/div/div[2]/div/label/div</value>
      <webElementGuid>e03c4c44-b608-4732-9739-99ff43752267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>af9c35de-eac6-4284-ae5a-ceb6510c9bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
