<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Got it</name>
   <tag></tag>
   <elementGuidId>188d7240-d2e5-4c0e-a6f9-d71555e77e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#got_it</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='got_it']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Got it!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c440ed4-e4ee-4699-b746-717eda6f7da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>got_it</value>
      <webElementGuid>bdb01d5b-7933-4384-8bed-8ef892edea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>cancel()</value>
      <webElementGuid>459e34a7-0b73-4ee5-a457-c2e67113a088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary accountalert-background</value>
      <webElementGuid>662ad46b-c40e-4d54-bbaa-fcb4fa16e154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Got it!</value>
      <webElementGuid>79905fb9-3bb8-4539-99e3-32aa028bf718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;got_it&quot;)</value>
      <webElementGuid>d1d5b5c4-2577-43a2-8f96-458531594463</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='got_it']</value>
      <webElementGuid>08fe39e3-4653-4917-8aa9-5d0db9f8561f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/following::button[1]</value>
      <webElementGuid>4bb6fbe3-cf0d-4116-896e-87a4cc3ec614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Got it!']/parent::*</value>
      <webElementGuid>20904711-04c0-45ac-bc17-b0fb336f3ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div[2]/button</value>
      <webElementGuid>d97bf31c-e9bc-4610-89ac-07bf211038a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'got_it' and (text() = 'Got it!' or . = 'Got it!')]</value>
      <webElementGuid>57e909a1-8e64-426f-ba2c-15054e6a036b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
