<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gender_XqNaEv eJE9fb</name>
   <tag></tag>
   <elementGuidId>92e89f48-ad5a-4c6f-8be8-d79e604bf358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.XqNaEv.eJE9fb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb170f0e-80bb-4c41-87d9-c1068c22763c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>XqNaEv eJE9fb</value>
      <webElementGuid>678d31be-04ea-46c3-ad05-484aa4e299fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;nt6sNV JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-2-12&quot;]/div[@class=&quot;DOjaWF gdgoEp col-12-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_0BvurA&quot;]/section[@class=&quot;_2OLUF3 _6gqfMo&quot;]/label[@class=&quot;tJjCVx cnLG4I&quot;]/div[@class=&quot;XqNaEv eJE9fb&quot;]</value>
      <webElementGuid>ee88c1b9-9483-46cf-acad-1e20739e8c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/label/div</value>
      <webElementGuid>7ac40c3a-5c8b-4aff-80e6-edfe6f98e077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>f2121375-8a56-46e1-8f0e-7936884a2926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
