<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_B - A DOUGLAS BLACK</name>
   <tag></tag>
   <elementGuidId>1ab24995-de06-4c8b-9060-7419220f4d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d78a72d9-d067-4c26-86db-a3efab5a1f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c165-31</value>
      <webElementGuid>cdafaa65-7775-4776-93da-489681b289b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-3</value>
      <webElementGuid>6389242f-0aea-4792-8a9c-02d854c55185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B - A DOUGLAS BLACK</value>
      <webElementGuid>dd914cc0-cf65-4bf6-aba3-6e7e090c9944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-3&quot;)</value>
      <webElementGuid>9526bd1b-87fc-414e-bbc4-e062b6b8e491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CSR_Customer_Employer/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>b1d23df2-0f9f-46b5-8aed-a4a6ec798896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-3']</value>
      <webElementGuid>2c7370da-d03c-43c6-b0cc-1dfa99c509a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='id_matselect_emprInfo_Borrower_1']/div/div</value>
      <webElementGuid>f208073f-4f36-4c4b-ac85-b3b733e0812d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='employer name test'])[1]/following::div[28]</value>
      <webElementGuid>c8404868-05b7-4b3e-9feb-31c99239b722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Last Verified com'])[2]/following::div[40]</value>
      <webElementGuid>df411a04-ab8c-4dd5-94be-86c1c280b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower/Co-Borrower'])[2]/preceding::div[3]</value>
      <webElementGuid>f69349f7-a86c-4889-827e-a925322296fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>9e9f1bb9-09fe-4e54-a0d9-c500da08a791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-3' and (text() = 'B - A DOUGLAS BLACK' or . = 'B - A DOUGLAS BLACK')]</value>
      <webElementGuid>4da0c0a7-96da-4723-9465-d4a81c1ef1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
