<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Open_myIframe</name>
   <tag></tag>
   <elementGuidId>8464edcf-d526-49d1-b68a-97371cee8e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='myIframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myIframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#myIframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e70a2172-f573-45c2-9b55-547bde7f0a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://toyotaqa.loanmanager.central.conduent.com/ReleaseTest/csr/csrnew/#/dashboard/customer/customerinfo/IL</value>
      <webElementGuid>8b1d546a-f9d6-4600-aca4-14226cdc2981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myIframe</value>
      <webElementGuid>ecc7dc38-bd84-47ac-8b5d-47858e3331c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-nofocus</value>
      <webElementGuid>6c3a4a02-44ed-4032-879c-8c68a5213855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b832f50d-4ab2-43ac-97bb-d79eab4eafba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this);</value>
      <webElementGuid>9ccf25cd-a218-4e88-83a8-f309116434a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myIframe&quot;)</value>
      <webElementGuid>ae38435d-319d-48cf-a653-ce7bd2ce44ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='myIframe']</value>
      <webElementGuid>9c883fcd-30b8-4a96-a5a9-9704faa2c327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d02655c1-e169-45d8-b68e-2e2959ba405e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://toyotaqa.loanmanager.central.conduent.com/ReleaseTest/csr/csrnew/#/dashboard/customer/customerinfo/IL' and @id = 'myIframe']</value>
      <webElementGuid>29044e13-ccf0-44ce-bc68-55dceb377946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
