<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BorrowerCo-Borrower_id_inp_emprInfo_H_cb0cdc</name>
   <tag></tag>
   <elementGuidId>a47f873a-ce06-452f-85e4-a4559fe9359f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_inp_emprInfo_HomePhone_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_inp_emprInfo_HomePhone_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;emp phone&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19dee9af-ed63-4692-b73d-f1d6551ea16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70b7f367-b6d5-46c3-a2b1-c98041aca77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>HomePhone</value>
      <webElementGuid>78407c5a-00d0-47f6-a8b0-9c40af6fcd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>23ac5a4b-5a62-4a19-9b30-ab64daed58de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control control-small-size ng-tns-c54-34 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>e50a5850-a45a-4824-9c69-b96bc2893220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_inp_emprInfo_HomePhone_1</value>
      <webElementGuid>c5b56959-bd4c-4568-ab87-47ac93f95938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21b2d137-569a-4202-81f0-c3d51d91bfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>93ab66ee-0f86-420d-bafe-a1a0183a0175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_inp_emprInfo_HomePhone_1&quot;)</value>
      <webElementGuid>fba9fab5-d7c3-483c-a458-a57e3dd954c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CSR_Customer_Employer/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>eda6769f-079f-47c1-9494-d05d7a9e9371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_inp_emprInfo_HomePhone_1']</value>
      <webElementGuid>ba4956a0-a922-4eab-a18f-6386edf2a057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_emprinfo_table_0']/tbody/tr[2]/td/div/div[2]/form/div/div/table/tr[4]/td/div[8]/div/div/div/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>f0a74c26-bb9f-43b3-9414-47160f6ac726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>14ce9cdd-35a0-4a13-91ea-65f9a85a1286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_inp_emprInfo_HomePhone_1']</value>
      <webElementGuid>e67377b9-6cf4-47f6-aa8a-89fa9e6612f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
