<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Info Last Verified com_id_inp_emprInf_f83241</name>
   <tag></tag>
   <elementGuidId>c5d0ca56-ef89-4be6-8f6b-635b580295e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_inp_emprInfo_Name1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_inp_emprInfo_Name1_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;employer name test *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b55339ea-577a-4816-982e-cc39c7ce256d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9fc019c-a788-4e5d-ae98-aa8c34ddb4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Name1</value>
      <webElementGuid>11af2d01-99b3-4627-8a73-14602fb146a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>43e646c5-ed73-4323-a698-cec4ae86bcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^!();_ .\-a-zA-Z0-9]/g, '');</value>
      <webElementGuid>8b74c271-2a7e-48e3-a77e-11558ef24cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control control-large-size ng-tns-c54-33 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-invalid</value>
      <webElementGuid>788a9146-ed2e-40db-840d-51c77782ca40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_inp_emprInfo_Name1_1</value>
      <webElementGuid>9ae66be7-fa7b-45be-8336-04934448a180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c5c8a01-820d-4dec-9e1c-b78f8e2d97ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_inp_emprInfo_Name1_1&quot;)</value>
      <webElementGuid>e45e247a-7b07-40fc-8cdd-52642ff197b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CSR_Customer_Employer/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>6c71e6f4-920a-4031-b34b-da91b87cb7f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_inp_emprInfo_Name1_1']</value>
      <webElementGuid>2fbbd0ba-21d5-4709-a167-14f476c7251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_emprinfo_table_0']/tbody/tr[2]/td/div/div[2]/form/div/div/table/tr[2]/td/div/div/div/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>64008044-f518-491c-aefe-52577ac00bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>f96c944e-3505-480b-9baa-084857882749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id_inp_emprInfo_Name1_1']</value>
      <webElementGuid>5e676cdc-4d88-4e1f-8e6c-916f5f7d6751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
