<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Edit DetailsAll fields with an (asterisk_22589b</name>
   <tag></tag>
   <elementGuidId>9633693d-5a8d-45c0-82d7-af9b97ab5dce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='id_table_emprinfo_table_0']/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.cdk-column-expandedDetail.mat-column-expandedDetail.ng-tns-c258-19.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Edit Details All fields with an *(asterisk) are required to save. Save Cancel Info Last Verified com Open calendar employer name test Borrower/Co-Borrower B - A DOUGLAS BLACK emp phone Text Opt In Ok to Call emp extension Address Line 1 emp add line 2 emp city emp State Texas emp EZip Change History Updated Updated By Employer Name Borrower/Co-Borrower Employer Phone Extension Employer Address row actions 01/31/2022 FXC C2 SMITH CUSTOM POOL A DOUGLAS BLACK Borrower (802) 618-3857 9310 PECOS STHOUSTON,Texas77055 12/21/2021 TF1 C2 SMITH CUSTOM POOL A DOUGLAS BLACK Borrower (802) 618-3857 02/07/2020 FIXU SMITH CUSTOM POOL A DOUGLAS BLACK Borrower (802) 618-3857&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>50db6a58-425d-4efa-9d19-5e1778d6eb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>ecfd9f14-0308-4d0d-bd04-e9e493f83a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-expandedDetail mat-column-expandedDetail ng-tns-c258-19 ng-star-inserted</value>
      <webElementGuid>4c4eec61-f184-4fd1-bc8c-bb08a00efba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b08b6807-6b9a-431c-a2b9-97753c0652a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit DetailsAll fields with an *(asterisk) are required to save.SaveCancelInfo Last Verified comemployer name test *B - A DOUGLAS BLACKBorrower/Co-Borrower *emp phoneText Opt InOk to Callemp extensionAddress Line 1emp add line 2emp cityTexasemp Stateemp EZipChange History Items per page: 5 1 – 3 of 3 UpdatedUpdated ByEmployer NameBorrower/Co-BorrowerEmployer PhoneExtensionEmployer Address 01/31/2022FXC C2 SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 9310 PECOS STHOUSTON,Texas7705512/21/2021TF1 C2 SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 02/07/2020FIXU SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 </value>
      <webElementGuid>c3f70e01-f658-4ee3-9dfd-c9c48cf4c190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_table_emprinfo_table_0&quot;)/tbody[1]/tr[@class=&quot;mat-row cdk-row example-detail-row ng-tns-c258-19 ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-expandedDetail mat-column-expandedDetail ng-tns-c258-19 ng-star-inserted&quot;]</value>
      <webElementGuid>fac6d240-c1f3-4f11-a34d-da5c77356fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CSR_Customer_Employer/Page_Loan Manager - Customer/iframe_Open_myIframe</value>
      <webElementGuid>e13512b5-2d6e-4d40-b30a-ad9668df85df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='id_table_emprinfo_table_0']/tbody/tr[2]/td</value>
      <webElementGuid>123d63ac-d360-43ea-9e5c-8fe4974ec770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RHF'])[1]/following::td[3]</value>
      <webElementGuid>835a36d1-a5c2-4094-8f99-d1c323c4fcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok to call'])[1]/following::td[6]</value>
      <webElementGuid>5115b1f6-1563-4739-96af-e4fa9fb790c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>7b532a1a-8e44-4e02-a4bf-2296e544bf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Edit DetailsAll fields with an *(asterisk) are required to save.SaveCancelInfo Last Verified comemployer name test *B - A DOUGLAS BLACKBorrower/Co-Borrower *emp phoneText Opt InOk to Callemp extensionAddress Line 1emp add line 2emp cityTexasemp Stateemp EZipChange History Items per page: 5 1 – 3 of 3 UpdatedUpdated ByEmployer NameBorrower/Co-BorrowerEmployer PhoneExtensionEmployer Address 01/31/2022FXC C2 SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 9310 PECOS STHOUSTON,Texas7705512/21/2021TF1 C2 SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 02/07/2020FIXU SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 ' or . = 'Edit DetailsAll fields with an *(asterisk) are required to save.SaveCancelInfo Last Verified comemployer name test *B - A DOUGLAS BLACKBorrower/Co-Borrower *emp phoneText Opt InOk to Callemp extensionAddress Line 1emp add line 2emp cityTexasemp Stateemp EZipChange History Items per page: 5 1 – 3 of 3 UpdatedUpdated ByEmployer NameBorrower/Co-BorrowerEmployer PhoneExtensionEmployer Address 01/31/2022FXC C2 SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 9310 PECOS STHOUSTON,Texas7705512/21/2021TF1 C2 SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 02/07/2020FIXU SMITH CUSTOM POOL A DOUGLAS BLACKBorrower (802) 618-3857 ')]</value>
      <webElementGuid>7eb59c8c-63c1-4051-9f84-b3ec1577ff1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
