<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember Me_remember</name>
   <tag></tag>
   <elementGuidId>994ee3cd-c553-457d-95af-3b308f7ad671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;remember&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='remember']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe8a1e9-39f6-4580-a944-5a283aec8284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>54b38ec8-c20e-41af-a309-d826c1dd2a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remember</value>
      <webElementGuid>beb19a53-e751-4edc-b1bc-2366037bff83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>loginData.RememberUserName</value>
      <webElementGuid>b5fc5161-5a20-4205-818b-7949583259c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-multiple</name>
      <type>Main</type>
      <value>remember</value>
      <webElementGuid>02e52b0e-3e45-4535-bc8c-0f71c142e470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-id</name>
      <type>Main</type>
      <value>0193</value>
      <webElementGuid>37775e1c-08da-4c62-9849-a505eb62adb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid</value>
      <webElementGuid>49e7e8a1-19f9-4aa3-bab7-c2cde8297a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-panel&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;text-left mb-lg ng-dirty ng-valid ng-valid-required&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;checkbox c-checkbox pull-left mt0&quot;]/label[1]/input[@class=&quot;ng-pristine ng-valid&quot;]</value>
      <webElementGuid>246fdd1c-5ac6-4feb-aa21-a491e453213e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='remember']</value>
      <webElementGuid>3b86f15e-eb2a-409e-9361-b29b0a40602f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-panel']/div[2]/form/div[7]/div/label/input</value>
      <webElementGuid>d57366f6-967e-459d-9db7-33a7829c7ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>7da18c38-eab4-4b81-8781-f3aa3b41fa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'remember']</value>
      <webElementGuid>a4d99893-d3e5-43e1-a1e5-8a67c309724d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
