<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Min1500030000400005000060000</name>
   <tag></tag>
   <elementGuidId>55518d5e-17ca-417b-bd0f-a548b5d0a2bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div[2]/div/div/div/section[2]/div[4]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>54d19586-9e14-4ead-8d5c-570758072374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Gn+jFg</value>
      <webElementGuid>0b88e814-a902-479d-9496-bd37b14b9e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Min₹15000₹30000₹40000₹50000₹60000</value>
      <webElementGuid>6823c36e-451c-4d83-b6d6-a5e051fc0e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_0BvurA&quot;]/section[@class=&quot;FR+9+z _2OLUF3&quot;]/div[@class=&quot;BXgIa-&quot;]/div[@class=&quot;suthUA&quot;]/select[@class=&quot;Gn+jFg&quot;]</value>
      <webElementGuid>40de3121-8c0b-4082-9df6-36e88dd3c723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div[2]/div/div/div/section[2]/div[4]/div/select</value>
      <webElementGuid>966e522a-93e9-4226-8939-e6e4958381ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[7]/following::select[1]</value>
      <webElementGuid>eb212a95-bef6-433a-bd34-a7939ccfda38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[6]/following::select[1]</value>
      <webElementGuid>adabb102-628b-48d6-8506-66aa2d88f3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[1]/preceding::select[1]</value>
      <webElementGuid>a98dd997-3759-49f7-9bfa-5ac973393523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/preceding::select[2]</value>
      <webElementGuid>c6f37e33-25d9-4a3f-a091-ca443d95d589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3c042ddc-16e6-46ee-9401-ca5ffefcade5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Min₹15000₹30000₹40000₹50000₹60000' or . = 'Min₹15000₹30000₹40000₹50000₹60000')]</value>
      <webElementGuid>a09c7d02-f750-4c9a-b76f-a974992dba14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
