<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Customer Info</name>
   <tag></tag>
   <elementGuidId>ca8fc19f-6b9f-4408-a102-b9739cae5d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xa_sidebar'])[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#side_nav_12 > #item > #xa_sidebar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Customer Info&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>495c34db-4045-46bf-a3ae-5c03d2198c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xa_sidebar</value>
      <webElementGuid>81f3c7f6-2133-447f-9da4-a159a5dd6c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>sidebar.nav.customer.CUSTOMERINFO</value>
      <webElementGuid>74e308ba-a318-4f5a-b306-2f2a0c03ca87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope ng-binding</value>
      <webElementGuid>a86f6a9d-39b9-4739-823d-426dbb7ad0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Info</value>
      <webElementGuid>76c4beb6-9714-4c04-8487-40dad6359d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side_nav_12&quot;)/a[@id=&quot;item&quot;]/span[@id=&quot;xa_sidebar&quot;]</value>
      <webElementGuid>ef863afc-2c25-41fd-81ac-30ddf182fba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xa_sidebar'])[12]</value>
      <webElementGuid>8b1d1cf5-254b-4386-b678-3df13e144b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='item']/span)[11]</value>
      <webElementGuid>38501b0d-9b63-4cd3-ab0b-1f923ccd6c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::span[1]</value>
      <webElementGuid>98a8aaa2-9610-4861-bcc2-1c4caad6cebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance History'])[1]/following::span[2]</value>
      <webElementGuid>6d6a14d4-0148-4ee3-95df-5090eaab8599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Services'])[1]/preceding::span[1]</value>
      <webElementGuid>85d3cbc1-0f1e-4b29-a53e-8b72449f7c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bankruptcy'])[1]/preceding::span[2]</value>
      <webElementGuid>22ff2a38-7c3e-4e3a-b010-43a38d13e765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Info']/parent::*</value>
      <webElementGuid>6f76fadd-3025-42e0-8677-052819b8ae33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a/span</value>
      <webElementGuid>6ac2f507-1c0c-4b17-b17b-59e3f8a8b5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xa_sidebar' and (text() = 'Customer Info' or . = 'Customer Info')]</value>
      <webElementGuid>41056373-4ee6-4357-9512-05342a58a069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
