<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Television</name>
   <tag></tag>
   <elementGuidId>c0602b8d-3f67-4f3e-85db-613e510d57be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jBYtJt.cNDIdi.CP4tVY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edae3721-0f3b-4a77-a585-5e21c395d440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Television</value>
      <webElementGuid>20326c20-57e8-4cd7-a177-d3c4a9a4b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jBYtJt cNDIdi CP4tVY</value>
      <webElementGuid>ecd8d570-c9c6-4694-b76e-cca799f1fb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/television-store?otracker=nmenu_sub_TVs%20and%20Appliances_0_Televisions&amp;otracker=nmenu_sub_TVs%20%26%20Appliances_0_Television</value>
      <webElementGuid>8e2b1113-2182-403e-9c17-7e3d90b06137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Television</value>
      <webElementGuid>121c170e-4eb4-4f4e-b5e9-f9716722b7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_5M58Mb&quot;]/div[@class=&quot;ACvr7K hTtFMH&quot;]/div[@class=&quot;bpjkJb&quot;]/div[@class=&quot;jzpKY6&quot;]/div[@class=&quot;wZsanD&quot;]/a[@class=&quot;jBYtJt cNDIdi CP4tVY&quot;]</value>
      <webElementGuid>325e07bb-8352-45e1-8ab6-02ee3b39a1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>bdace78e-bfa0-45b5-bcf5-18744893bbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Television')]</value>
      <webElementGuid>77e73dea-0919-4e48-85f2-cb8801f22cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offer Zone'])[1]/following::a[1]</value>
      <webElementGuid>b29f6030-cb49-4485-be2f-42fe5e40777c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::a[2]</value>
      <webElementGuid>1aed5922-5c13-47eb-9cb3-ca4ab4f92990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Launches'])[1]/preceding::a[1]</value>
      <webElementGuid>7ff672bd-dc4b-402f-a77b-147a767d4078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart &amp; Ultra HD'])[1]/preceding::a[2]</value>
      <webElementGuid>54f79d5c-3e40-4242-9712-bffc947ccabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Television']/parent::*</value>
      <webElementGuid>bb352956-b9f1-45af-ba47-765ad102681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/television-store?otracker=nmenu_sub_TVs%20and%20Appliances_0_Televisions&amp;otracker=nmenu_sub_TVs%20%26%20Appliances_0_Television')]</value>
      <webElementGuid>144a56af-eeab-4a9d-9869-fa6d1348fc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>3b176d16-9850-44e0-8595-8c7e096801c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Television' and @href = '/television-store?otracker=nmenu_sub_TVs%20and%20Appliances_0_Televisions&amp;otracker=nmenu_sub_TVs%20%26%20Appliances_0_Television' and (text() = 'Television' or . = 'Television')]</value>
      <webElementGuid>c910af95-b8ef-44bb-ab7b-17dd08e996f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
