<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Mobile Phones</name>
   <tag></tag>
   <elementGuidId>9c3ceaf1-9c8e-4463-91ff-57307d8d9268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1._0FYq1K</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>14c6092d-1926-48a9-bbe3-bd47b16341f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_0FYq1K</value>
      <webElementGuid>e310f69a-650e-4c93-96f1-0c0ecf51ce22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile Phones</value>
      <webElementGuid>ac326b65-3ea4-49dc-9fe2-a4faf113b125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;JxFEK3 _48O0EI&quot;]/div[@class=&quot;s8FW+c&quot;]/h1[@class=&quot;_0FYq1K&quot;]</value>
      <webElementGuid>bbb0b1e7-b0a3-4b2c-b30a-5aa4db7aa210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/h1</value>
      <webElementGuid>0f6585da-22ab-4dab-8b2e-e234363c1703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offer Zone'])[1]/following::h1[1]</value>
      <webElementGuid>8eaeaeea-50e9-4568-a756-1147b097900c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::h1[1]</value>
      <webElementGuid>5ace1e30-209e-47fb-9173-0430bb63b74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone 15'])[1]/preceding::h1[1]</value>
      <webElementGuid>9bd94f04-5a2f-417b-ae10-d231eab5b1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobile Phones']/parent::*</value>
      <webElementGuid>90599932-e565-42d1-8d32-ecc4c4cb407b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3a3a0db0-6e35-49b2-b90a-be9c3743e467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Mobile Phones' or . = 'Mobile Phones')]</value>
      <webElementGuid>6ce15754-9dfc-4e93-ad4f-8bb556291354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
