<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Electronics</name>
   <tag></tag>
   <elementGuidId>490e8e5e-1069-464b-b47c-eb88aeea8cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Electronics' or . = 'Electronics')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.TSD49J.nEqBzi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7b1715f-6fa1-4301-943e-90c0a561d006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TSD49J nEqBzi</value>
      <webElementGuid>39d39407-ff57-4fa7-a77b-06e7b6885770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Electronics</value>
      <webElementGuid>10dce2e1-9b1e-465a-bdb2-7bffa1da0641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_5M58Mb&quot;]/div[@class=&quot;ACvr7K hTtFMH&quot;]/div[@class=&quot;bpjkJb&quot;]/span[@class=&quot;TSD49J nEqBzi&quot;]</value>
      <webElementGuid>f4a7ef7e-e829-409f-93d3-7ab6df93a3e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/span</value>
      <webElementGuid>be568ff3-2442-4a98-8bd4-a2e37ef3df33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::span[1]</value>
      <webElementGuid>78a7df88-a3c7-4a03-a42b-483dafd98ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TVs &amp; Appliances'])[1]/preceding::span[1]</value>
      <webElementGuid>eebe1dc9-ee74-49d7-ba42-8846fedee007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men'])[1]/preceding::span[2]</value>
      <webElementGuid>eaeb9a6d-0ff4-4d63-aa28-c11bcf3b3ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Electronics']/parent::*</value>
      <webElementGuid>ee7ad965-518a-4381-98be-0141d1c37569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>6567b9c6-0cc9-4b10-9045-dd95c88feb56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Electronics' or . = 'Electronics')]</value>
      <webElementGuid>6f6eef7d-32f1-4059-af29-1074f4247646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
